server:
  port: 8081
  servlet:
    context-path: /auth
logging:
  level:
    org.springframework.boot.autoconfigure: DEBUG

spring:
    application:
        name: iam-service
    datasource:
      url: jdbc:postgresql://localhost:5432/team2db
      username: postgres
      password: root
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 30000
        max-lifetime: 1800000
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    messages:
      encoding: 'UTF-8'
      use-code-as-default-message: true
      basename: i18n/labels
      cache-duration: 560
